/* Generated By:JJTree: Do not edit this line. ASTPhpSimpleValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpSimpleValue extends SimpleNode {
  public ASTPhpSimpleValue(int id) {
    super(id);
  }

  public ASTPhpSimpleValue(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f09d2e5cfd66dbc15be6d1e99b504915 (do not edit this line) */
