/* Generated By:JJTree: Do not edit this line. ASTPhpClassDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpClassDefinition extends SimpleNode {
  public ASTPhpClassDefinition(int id) {
    super(id);
  }

  public ASTPhpClassDefinition(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccf03e1dd007900f207bc9867acedbe5 (do not edit this line) */
