/* Generated By:JJTree: Do not edit this line. ASTPhpRootBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpRootBlock extends SimpleNode {
  public ASTPhpRootBlock(int id) {
    super(id);
  }

  public ASTPhpRootBlock(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=86dd109d53ea946eac7fb38bd0de5968 (do not edit this line) */
