/* Generated By:JJTree: Do not edit this line. ASTJsValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsValue extends SimpleNode {
  public ASTJsValue(int id) {
    super(id);
  }

  public ASTJsValue(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2f1f8d0589a14ff7f07d1ed570b2e58b (do not edit this line) */
