/* Generated By:JJTree: Do not edit this line. ASTJsFunctionDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsFunctionDefinition extends SimpleNode {
  public ASTJsFunctionDefinition(int id) {
    super(id);
  }

  public ASTJsFunctionDefinition(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df51fa86c24fb8935a2ad3e3a9d729fc (do not edit this line) */
