/* Generated By:JJTree: Do not edit this line. ASTJsThrowStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsThrowStatement extends SimpleNode {
  public ASTJsThrowStatement(int id) {
    super(id);
  }

  public ASTJsThrowStatement(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1ea3119b87bb7229a09a00308f377c21 (do not edit this line) */
