/* Generated By:JJTree: Do not edit this line. ASTJsForParameterList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsForParameterList extends SimpleNode {
  public ASTJsForParameterList(int id) {
    super(id);
  }

  public ASTJsForParameterList(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=882ab39bc60fa8d3ea81cc9958d29a6f (do not edit this line) */
