/* Generated By:JJTree: Do not edit this line. ASTJsAnonymousFunction.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsAnonymousFunction extends SimpleNode {
  public ASTJsAnonymousFunction(int id) {
    super(id);
  }

  public ASTJsAnonymousFunction(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=573acaa12b060ce490db31ab161394db (do not edit this line) */
