/* Generated By:JJTree: Do not edit this line. ASTPhpClassDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpClassDefinition extends SimpleNode {
  public ASTPhpClassDefinition(int id) {
    super(id);
  }

  public ASTPhpClassDefinition(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e7ef6f2fffd61b34c546c0a1d8d2fd8a (do not edit this line) */
