/* Generated By:JJTree: Do not edit this line. ASTPhpFunctionDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpFunctionDefinition extends SimpleNode {
  public ASTPhpFunctionDefinition(int id) {
    super(id);
  }

  public ASTPhpFunctionDefinition(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e54b7cd05daa20c1f7f2ebf87a21d88c (do not edit this line) */
