/* Generated By:JJTree: Do not edit this line. ASTPhpInterfaceDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpInterfaceDefinition extends SimpleNode {
  public ASTPhpInterfaceDefinition(int id) {
    super(id);
  }

  public ASTPhpInterfaceDefinition(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e2a8f504ebe0289fe0b806401693778a (do not edit this line) */
