/* Generated By:JJTree: Do not edit this line. ASTPhpIfStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpIfStatement extends SimpleNode {
  public ASTPhpIfStatement(int id) {
    super(id);
  }

  public ASTPhpIfStatement(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be2e7d6bd99ea9c25445dd44e2bdee19 (do not edit this line) */
