/* Generated By:JJTree: Do not edit this line. ASTPhpVariableAssignment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpVariableAssignment extends SimpleNode {
  public ASTPhpVariableAssignment(int id) {
    super(id);
  }

  public ASTPhpVariableAssignment(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2cd24ceed664e365c4d054e710dbf78e (do not edit this line) */
