/* Generated By:JJTree: Do not edit this line. ASTPhpComment.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpComment extends SimpleNode {
  public ASTPhpComment(int id) {
    super(id);
  }

  public ASTPhpComment(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c19e00e319866f55968c34f50b021820 (do not edit this line) */
