/* Generated By:JJTree: Do not edit this line. ASTPhpSelectArray.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpSelectArray extends SimpleNode {
  public ASTPhpSelectArray(int id) {
    super(id);
  }

  public ASTPhpSelectArray(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=180cc1dfbae59512781ec37901bd3037 (do not edit this line) */
