/* Generated By:JavaCC: Do not edit this line. InternetApplicationTreeConstants.java Version 4.1d1 */
package org.openiaml.iacleaner.ast;

public interface InternetApplicationTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTPHPROOTBLOCK = 2;
  public int JJTPHPBLOCK = 3;
  public int JJTPHPINLINEHTMLBLOCK = 4;
  public int JJTPHPSTATEMENT = 5;
  public int JJTPHPLANGUAGESTATEMENT = 6;
  public int JJTPHPVALUE = 7;
  public int JJTPHPSIMPLEVALUE = 8;
  public int JJTPHPARGUMENTLIST = 9;
  public int JJTPHPVARIABLELIST = 10;
  public int JJTPHPFUNCTIONDEFINITION = 11;
  public int JJTPHPFUNCTIONARGUMENTLIST = 12;
  public int JJTPHPIFSTATEMENT = 13;
  public int JJTPHPCLASSDEFINITION = 14;
  public int JJTPHPINTERFACEDEFINITION = 15;
  public int JJTPHPINTERFACELIST = 16;
  public int JJTPHPCLASSBLOCK = 17;
  public int JJTPHPINTERFACEBLOCK = 18;
  public int JJTHTMLBLOCK = 19;
  public int JJTHTMLTAG = 20;
  public int JJTHTMLCLOSINGTAG = 21;
  public int JJTHTMLTAGATTRIBUTE = 22;
  public int JJTHTMLTEXTBLOCK = 23;
  public int JJTHTMLCOMMENT = 24;


  public String[] jjtNodeName = {
    "Start",
    "Block",
    "PhpRootBlock",
    "PhpBlock",
    "PhpInlineHtmlBlock",
    "PhpStatement",
    "PhpLanguageStatement",
    "PhpValue",
    "PhpSimpleValue",
    "PhpArgumentList",
    "PhpVariableList",
    "PhpFunctionDefinition",
    "PhpFunctionArgumentList",
    "PhpIfStatement",
    "PhpClassDefinition",
    "PhpInterfaceDefinition",
    "PhpInterfaceList",
    "PhpClassBlock",
    "PhpInterfaceBlock",
    "HtmlBlock",
    "HtmlTag",
    "HtmlClosingTag",
    "HtmlTagAttribute",
    "HtmlTextBlock",
    "HtmlComment",
  };
}
/* JavaCC - OriginalChecksum=83aa451c9973598ab0666c866a46036f (do not edit this line) */
