/* Generated By:JJTree&JavaCC: Do not edit this line. InternetApplicationConstants.java */
package org.openiaml.iacleaner.ast;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InternetApplicationConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ECHO_STATEMENT = 17;
  /** RegularExpression Id. */
  int FUNCTION_STATEMENT = 18;
  /** RegularExpression Id. */
  int RETURN_STATEMENT = 19;
  /** RegularExpression Id. */
  int GLOBAL_STATEMENT = 20;
  /** RegularExpression Id. */
  int NEW_STATEMENT = 21;
  /** RegularExpression Id. */
  int VAR_STATEMENT = 22;
  /** RegularExpression Id. */
  int CLASS_STATEMENT = 23;
  /** RegularExpression Id. */
  int INTERFACE_STATEMENT = 24;
  /** RegularExpression Id. */
  int IMPLEMENTS_STATEMENT = 25;
  /** RegularExpression Id. */
  int EXTENDS_STATEMENT = 26;
  /** RegularExpression Id. */
  int ACCESS_MODIFIER = 27;
  /** RegularExpression Id. */
  int PHP_IF_STATEMENT = 28;
  /** RegularExpression Id. */
  int PHP_ELSE_STATEMENT = 29;
  /** RegularExpression Id. */
  int STRING = 30;
  /** RegularExpression Id. */
  int DECIMAL = 31;
  /** RegularExpression Id. */
  int HEXADECIMAL = 32;
  /** RegularExpression Id. */
  int PHP_BUILTIN = 33;
  /** RegularExpression Id. */
  int PHP_FUNCTION_NAME = 34;
  /** RegularExpression Id. */
  int PHP_SINGLE_COMMENT = 35;
  /** RegularExpression Id. */
  int PHP_MULTI_COMMENT = 36;
  /** RegularExpression Id. */
  int PHP_VARIABLE = 37;
  /** RegularExpression Id. */
  int PHP_OPERATOR = 38;
  /** RegularExpression Id. */
  int PHP_BLOCK_END = 39;
  /** RegularExpression Id. */
  int PHP_BLOCK_BEGIN = 40;
  /** RegularExpression Id. */
  int HTML_OPEN_TAG = 41;
  /** RegularExpression Id. */
  int HTML_CLOSE_TAG = 42;
  /** RegularExpression Id. */
  int HTML_CLOSING_TAG = 43;
  /** RegularExpression Id. */
  int HTML_TAG_NAME = 44;
  /** RegularExpression Id. */
  int LETTER = 45;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_NAME = 46;
  /** RegularExpression Id. */
  int HTML_STRING = 47;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_EQUALS = 48;
  /** RegularExpression Id. */
  int HTML_TEXT_BLOCK = 49;

  /** Lexical state. */
  int HTML_STATE = 0;
  /** Lexical state. */
  int HTML_TAG_STATE = 1;
  /** Lexical state. */
  int HTML_OPENING_TAG = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"echo\"",
    "\"function\"",
    "\"return\"",
    "\"global\"",
    "\"new\"",
    "\"var\"",
    "\"class\"",
    "\"interface\"",
    "\"implements\"",
    "\"extends\"",
    "<ACCESS_MODIFIER>",
    "\"if\"",
    "\"else\"",
    "<STRING>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "<PHP_BUILTIN>",
    "<PHP_FUNCTION_NAME>",
    "<PHP_SINGLE_COMMENT>",
    "<PHP_MULTI_COMMENT>",
    "<PHP_VARIABLE>",
    "<PHP_OPERATOR>",
    "\"?>\"",
    "\"<?php\"",
    "\"<\"",
    "\">\"",
    "\"</\"",
    "<HTML_TAG_NAME>",
    "<LETTER>",
    "<HTML_ATTRIBUTE_NAME>",
    "<HTML_STRING>",
    "\"=\"",
    "<HTML_TEXT_BLOCK>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
  };

}
