/* Generated By:JavaCC: Do not edit this line. InternetApplicationTreeConstants.java Version 4.1d1 */
package org.openiaml.iacleaner.ast;

public interface InternetApplicationTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTARTJS = 1;
  public int JJTBLOCK = 2;
  public int JJTPHPROOTBLOCK = 3;
  public int JJTPHPBLOCK = 4;
  public int JJTPHPINLINEHTMLBLOCK = 5;
  public int JJTPHPSTATEMENT = 6;
  public int JJTPHPLANGUAGESTATEMENT = 7;
  public int JJTPHPVALUE = 8;
  public int JJTPHPSIMPLEVALUE = 9;
  public int JJTPHPARGUMENTLIST = 10;
  public int JJTPHPVARIABLELIST = 11;
  public int JJTPHPFUNCTIONDEFINITION = 12;
  public int JJTPHPFUNCTIONARGUMENTLIST = 13;
  public int JJTPHPIFSTATEMENT = 14;
  public int JJTPHPCLASSDEFINITION = 15;
  public int JJTPHPINTERFACEDEFINITION = 16;
  public int JJTPHPINTERFACELIST = 17;
  public int JJTPHPCLASSBLOCK = 18;
  public int JJTPHPINTERFACEBLOCK = 19;
  public int JJTHTMLBLOCK = 20;
  public int JJTHTMLSCRIPTTAG = 21;
  public int JJTHTMLTAG = 22;
  public int JJTHTMLCLOSINGTAG = 23;
  public int JJTHTMLTAGATTRIBUTE = 24;
  public int JJTHTMLTEXTBLOCK = 25;
  public int JJTHTMLCOMMENT = 26;
  public int JJTJSBLOCK = 27;
  public int JJTJSSTATEMENT = 28;
  public int JJTJSLANGUAGESTATEMENT = 29;
  public int JJTJSVALUE = 30;
  public int JJTJSSIMPLEVALUE = 31;
  public int JJTJSARGUMENTLIST = 32;
  public int JJTJSVARIABLELIST = 33;
  public int JJTJSFUNCTIONDEFINITION = 34;
  public int JJTJSFUNCTIONARGUMENTLIST = 35;
  public int JJTJSIFSTATEMENT = 36;


  public String[] jjtNodeName = {
    "Start",
    "StartJs",
    "Block",
    "PhpRootBlock",
    "PhpBlock",
    "PhpInlineHtmlBlock",
    "PhpStatement",
    "PhpLanguageStatement",
    "PhpValue",
    "PhpSimpleValue",
    "PhpArgumentList",
    "PhpVariableList",
    "PhpFunctionDefinition",
    "PhpFunctionArgumentList",
    "PhpIfStatement",
    "PhpClassDefinition",
    "PhpInterfaceDefinition",
    "PhpInterfaceList",
    "PhpClassBlock",
    "PhpInterfaceBlock",
    "HtmlBlock",
    "HtmlScriptTag",
    "HtmlTag",
    "HtmlClosingTag",
    "HtmlTagAttribute",
    "HtmlTextBlock",
    "HtmlComment",
    "JsBlock",
    "JsStatement",
    "JsLanguageStatement",
    "JsValue",
    "JsSimpleValue",
    "JsArgumentList",
    "JsVariableList",
    "JsFunctionDefinition",
    "JsFunctionArgumentList",
    "JsIfStatement",
  };
}
/* JavaCC - OriginalChecksum=36951e4ddc3b62e6946da55673a1d976 (do not edit this line) */
