/* Generated By:JJTree: Do not edit this line. ASTPhpArgumentList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpArgumentList extends SimpleNode {
  public ASTPhpArgumentList(int id) {
    super(id);
  }

  public ASTPhpArgumentList(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6fb22b94ed5ba99a6234bb91567f1ddf (do not edit this line) */
