/* Generated By:JJTree: Do not edit this line. ASTPhpValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpValue extends SimpleNode {
  public ASTPhpValue(int id) {
    super(id);
  }

  public ASTPhpValue(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=49aec54e3c2866c70d1e6e7b20fdd866 (do not edit this line) */
