/* Generated By:JJTree: Do not edit this line. ASTPhpInterfaceDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpInterfaceDefinition extends SimpleNode {
  public ASTPhpInterfaceDefinition(int id) {
    super(id);
  }

  public ASTPhpInterfaceDefinition(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07a0c720283bf30aa6442756d4e784be (do not edit this line) */
