/* Generated By:JJTree: Do not edit this line. ASTPhpIfStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpIfStatement extends SimpleNode {
  public ASTPhpIfStatement(int id) {
    super(id);
  }

  public ASTPhpIfStatement(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=16376132e021b3d5a2ade3b320cb40c5 (do not edit this line) */
