/* Generated By:JJTree&JavaCC: Do not edit this line. PhpPageConstants.java */
package org.openiaml.iacleaner.ast.php;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PhpPageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ECHO_STATEMENT = 11;
  /** RegularExpression Id. */
  int FUNCTION_STATEMENT = 12;
  /** RegularExpression Id. */
  int RETURN_STATEMENT = 13;
  /** RegularExpression Id. */
  int GLOBAL_STATEMENT = 14;
  /** RegularExpression Id. */
  int NEW_STATEMENT = 15;
  /** RegularExpression Id. */
  int OR_STATEMENT = 16;
  /** RegularExpression Id. */
  int VAR_STATEMENT = 17;
  /** RegularExpression Id. */
  int CLASS_STATEMENT = 18;
  /** RegularExpression Id. */
  int INTERFACE_STATEMENT = 19;
  /** RegularExpression Id. */
  int IMPLEMENTS_STATEMENT = 20;
  /** RegularExpression Id. */
  int EXTENDS_STATEMENT = 21;
  /** RegularExpression Id. */
  int ACCESS_MODIFIER = 22;
  /** RegularExpression Id. */
  int PHP_TRY_STATEMENT = 23;
  /** RegularExpression Id. */
  int PHP_CATCH_STATEMENT = 24;
  /** RegularExpression Id. */
  int PHP_THROW_STATEMENT = 25;
  /** RegularExpression Id. */
  int PHP_FINALLY_STATEMENT = 26;
  /** RegularExpression Id. */
  int PHP_DIE_STATEMENT = 27;
  /** RegularExpression Id. */
  int PHP_EXIT_STATEMENT = 28;
  /** RegularExpression Id. */
  int PHP_IF_STATEMENT = 29;
  /** RegularExpression Id. */
  int PHP_ELSE_STATEMENT = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int STRING_SQ = 32;
  /** RegularExpression Id. */
  int DECIMAL = 33;
  /** RegularExpression Id. */
  int HEXADECIMAL = 34;
  /** RegularExpression Id. */
  int PHP_BUILTIN = 35;
  /** RegularExpression Id. */
  int PHP_FUNCTION_NAME = 36;
  /** RegularExpression Id. */
  int PHP_VARIABLE = 37;
  /** RegularExpression Id. */
  int PHP_OBJECT_OPERATOR = 38;
  /** RegularExpression Id. */
  int PHP_OPERATOR = 39;
  /** RegularExpression Id. */
  int PHP_PREFIX_OPERATOR = 40;
  /** RegularExpression Id. */
  int PHP_BLOCK_END = 41;
  /** RegularExpression Id. */
  int PHP_BLOCK_BEGIN = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int PHP_WITHIN_COMMENT = 1;
  /** Lexical state. */
  int PHP_WITHIN_COMMENT_SINGLE = 2;
  /** Lexical state. */
  int HTML_STATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"echo\"",
    "\"function\"",
    "\"return\"",
    "\"global\"",
    "\"new\"",
    "\"or\"",
    "\"var\"",
    "\"class\"",
    "\"interface\"",
    "\"implements\"",
    "\"extends\"",
    "<ACCESS_MODIFIER>",
    "\"try\"",
    "\"catch\"",
    "\"throw\"",
    "\"finally\"",
    "\"die\"",
    "\"exit\"",
    "\"if\"",
    "\"else\"",
    "<STRING>",
    "<STRING_SQ>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "<PHP_BUILTIN>",
    "<PHP_FUNCTION_NAME>",
    "<PHP_VARIABLE>",
    "\"::\"",
    "<PHP_OPERATOR>",
    "\"!\"",
    "\"?>\"",
    "\"<?php\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
