/* Generated By:JJTree: Do not edit this line. ASTJsInlineArray.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsInlineArray extends SimpleNode {
  public ASTJsInlineArray(int id) {
    super(id);
  }

  public ASTJsInlineArray(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9faf232802ad828769b54cd90a807551 (do not edit this line) */
