/* Generated By:JJTree: Do not edit this line. ASTJsSelectArray.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsSelectArray extends SimpleNode {
  public ASTJsSelectArray(int id) {
    super(id);
  }

  public ASTJsSelectArray(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=505cb1a713912a0f5fb589c5c0b4ce5a (do not edit this line) */
