/* Generated By:JJTree: Do not edit this line. ASTPhpBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpBlock extends SimpleNode {
  public ASTPhpBlock(int id) {
    super(id);
  }

  public ASTPhpBlock(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0b512efe3b0a15d04992c78a86fa01a2 (do not edit this line) */
