/* Generated By:JJTree: Do not edit this line. ASTPhpStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.php;

public class ASTPhpStatement extends SimpleNode {
  public ASTPhpStatement(int id) {
    super(id);
  }

  public ASTPhpStatement(PhpPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PhpPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c0f8383f0cc37f24949f1b68e83ce684 (do not edit this line) */
