/* Generated By:JJTree: Do not edit this line. ASTJsInlineArray.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsInlineArray extends SimpleNode {
  public ASTJsInlineArray(int id) {
    super(id);
  }

  public ASTJsInlineArray(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=545ac9d05e349aa6c2028cf5a04c2c56 (do not edit this line) */
