/* Generated By:JJTree: Do not edit this line. ASTJsChainedOperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTJsChainedOperator extends SimpleNode {
  public ASTJsChainedOperator(int id) {
    super(id);
  }

  public ASTJsChainedOperator(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c07f76ab22869636b6fb110b24885258 (do not edit this line) */
