/* Generated By:JJTree: Do not edit this line. ASTPhpValuePossiblyWrapped.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpValuePossiblyWrapped extends SimpleNode {
  public ASTPhpValuePossiblyWrapped(int id) {
    super(id);
  }

  public ASTPhpValuePossiblyWrapped(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b86440fe6b5c61ca6e3c41b2109a7d54 (do not edit this line) */
