/* Generated By:JJTree: Do not edit this line. ASTPhpBlockEnd.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpBlockEnd extends SimpleNode {
  public ASTPhpBlockEnd(int id) {
    super(id);
  }

  public ASTPhpBlockEnd(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=def7322aa333f1ae6ecb66239c459531 (do not edit this line) */
