/* Generated By:JJTree: Do not edit this line. ASTPhpLanguageStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpLanguageStatement extends SimpleNode {
  public ASTPhpLanguageStatement(int id) {
    super(id);
  }

  public ASTPhpLanguageStatement(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eed9b719cae65e1fd024ce75a114d5d3 (do not edit this line) */
