/* Generated By:JJTree: Do not edit this line. ASTPhpClassBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast;

public class ASTPhpClassBlock extends SimpleNode {
  public ASTPhpClassBlock(int id) {
    super(id);
  }

  public ASTPhpClassBlock(InternetApplication p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(InternetApplicationVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=17bc9bce5f3cb6e2bc436c27a15ee67e (do not edit this line) */
