/* Generated By:JJTree&JavaCC: Do not edit this line. InternetApplicationConstants.java */
package org.openiaml.iacleaner.ast;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InternetApplicationConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ECHO_STATEMENT = 23;
  /** RegularExpression Id. */
  int FUNCTION_STATEMENT = 24;
  /** RegularExpression Id. */
  int RETURN_STATEMENT = 25;
  /** RegularExpression Id. */
  int GLOBAL_STATEMENT = 26;
  /** RegularExpression Id. */
  int NEW_STATEMENT = 27;
  /** RegularExpression Id. */
  int OR_STATEMENT = 28;
  /** RegularExpression Id. */
  int VAR_STATEMENT = 29;
  /** RegularExpression Id. */
  int CLASS_STATEMENT = 30;
  /** RegularExpression Id. */
  int INTERFACE_STATEMENT = 31;
  /** RegularExpression Id. */
  int IMPLEMENTS_STATEMENT = 32;
  /** RegularExpression Id. */
  int EXTENDS_STATEMENT = 33;
  /** RegularExpression Id. */
  int ACCESS_MODIFIER = 34;
  /** RegularExpression Id. */
  int PHP_TRY_STATEMENT = 35;
  /** RegularExpression Id. */
  int PHP_CATCH_STATEMENT = 36;
  /** RegularExpression Id. */
  int PHP_THROW_STATEMENT = 37;
  /** RegularExpression Id. */
  int PHP_FINALLY_STATEMENT = 38;
  /** RegularExpression Id. */
  int PHP_DIE_STATEMENT = 39;
  /** RegularExpression Id. */
  int PHP_EXIT_STATEMENT = 40;
  /** RegularExpression Id. */
  int PHP_IF_STATEMENT = 41;
  /** RegularExpression Id. */
  int PHP_ELSE_STATEMENT = 42;
  /** RegularExpression Id. */
  int STRING = 43;
  /** RegularExpression Id. */
  int STRING_SQ = 44;
  /** RegularExpression Id. */
  int DECIMAL = 45;
  /** RegularExpression Id. */
  int HEXADECIMAL = 46;
  /** RegularExpression Id. */
  int PHP_BUILTIN = 47;
  /** RegularExpression Id. */
  int PHP_FUNCTION_NAME = 48;
  /** RegularExpression Id. */
  int PHP_VARIABLE = 49;
  /** RegularExpression Id. */
  int PHP_OBJECT_OPERATOR = 50;
  /** RegularExpression Id. */
  int PHP_OPERATOR = 51;
  /** RegularExpression Id. */
  int PHP_PREFIX_OPERATOR = 52;
  /** RegularExpression Id. */
  int PHP_BLOCK_END = 53;
  /** RegularExpression Id. */
  int PHP_BLOCK_BEGIN = 54;
  /** RegularExpression Id. */
  int HTML_OPEN_TAG = 55;
  /** RegularExpression Id. */
  int HTML_CLOSE_TAG = 56;
  /** RegularExpression Id. */
  int HTML_CLOSE_TAG_XHTML = 57;
  /** RegularExpression Id. */
  int HTML_CLOSING_TAG = 58;
  /** RegularExpression Id. */
  int HTML_TAG_NAME = 59;
  /** RegularExpression Id. */
  int LETTER = 60;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_NAME = 61;
  /** RegularExpression Id. */
  int HTML_STRING = 62;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_EQUALS = 63;
  /** RegularExpression Id. */
  int HTML_TEXT_BLOCK = 64;
  /** RegularExpression Id. */
  int HTML_COMMENT_START = 65;

  /** Lexical state. */
  int HTML_STATE = 0;
  /** Lexical state. */
  int HTML_TAG_STATE = 1;
  /** Lexical state. */
  int HTML_OPENING_TAG = 2;
  /** Lexical state. */
  int DEFAULT = 3;
  /** Lexical state. */
  int PHP_WITHIN_COMMENT = 4;
  /** Lexical state. */
  int PHP_WITHIN_COMMENT_SINGLE = 5;
  /** Lexical state. */
  int HTML_WITHIN_COMMENT = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 20>",
    "<token of kind 21>",
    "<token of kind 22>",
    "\"echo\"",
    "\"function\"",
    "\"return\"",
    "\"global\"",
    "\"new\"",
    "\"or\"",
    "\"var\"",
    "\"class\"",
    "\"interface\"",
    "\"implements\"",
    "\"extends\"",
    "<ACCESS_MODIFIER>",
    "\"try\"",
    "\"catch\"",
    "\"throw\"",
    "\"finally\"",
    "\"die\"",
    "\"exit\"",
    "\"if\"",
    "\"else\"",
    "<STRING>",
    "<STRING_SQ>",
    "<DECIMAL>",
    "<HEXADECIMAL>",
    "<PHP_BUILTIN>",
    "<PHP_FUNCTION_NAME>",
    "<PHP_VARIABLE>",
    "\"::\"",
    "<PHP_OPERATOR>",
    "\"!\"",
    "\"?>\"",
    "\"<?php\"",
    "\"<\"",
    "\">\"",
    "\"/>\"",
    "\"</\"",
    "<HTML_TAG_NAME>",
    "<LETTER>",
    "<HTML_ATTRIBUTE_NAME>",
    "<HTML_STRING>",
    "\"=\"",
    "<HTML_TEXT_BLOCK>",
    "\"<!--\"",
    "\"-->\"",
    "<token of kind 67>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
  };

}
