/* Generated By:JavaCC: Do not edit this line. InternetApplicationTreeConstants.java Version 4.1d1 */
package org.openiaml.iacleaner.ast;

public interface InternetApplicationTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTPHPROOTBLOCK = 2;
  public int JJTPHPBLOCK = 3;
  public int JJTPHPINLINEHTMLBLOCK = 4;
  public int JJTPHPSTATEMENT = 5;
  public int JJTPHPLANGUAGESTATEMENT = 6;
  public int JJTPHPVARIABLEASSIGNMENT = 7;
  public int JJTPHPFUNCTIONCALL = 8;
  public int JJTPHPORSOMETHING = 9;
  public int JJTPHPTRYCATCHBLOCK = 10;
  public int JJTPHPVALUE = 11;
  public int JJTPHPVALUEPOSSIBLYWRAPPED = 12;
  public int JJTPHPSIMPLEVALUE = 13;
  public int JJTPHPSELECTARRAY = 14;
  public int JJTPHPARGUMENTLIST = 15;
  public int JJTPHPVARIABLELIST = 16;
  public int JJTPHPFUNCTIONDEFINITION = 17;
  public int JJTPHPFUNCTIONARGUMENTLIST = 18;
  public int JJTPHPIFSTATEMENT = 19;
  public int JJTPHPCLASSDEFINITION = 20;
  public int JJTPHPINTERFACEDEFINITION = 21;
  public int JJTPHPINTERFACELIST = 22;
  public int JJTPHPCLASSBLOCK = 23;
  public int JJTPHPINTERFACEBLOCK = 24;
  public int JJTHTMLBLOCK = 25;
  public int JJTHTMLTAG = 26;
  public int JJTHTMLCLOSINGTAG = 27;
  public int JJTHTMLTAGATTRIBUTE = 28;
  public int JJTHTMLTEXTBLOCK = 29;
  public int JJTHTMLCOMMENT = 30;


  public String[] jjtNodeName = {
    "Start",
    "Block",
    "PhpRootBlock",
    "PhpBlock",
    "PhpInlineHtmlBlock",
    "PhpStatement",
    "PhpLanguageStatement",
    "PhpVariableAssignment",
    "PhpFunctionCall",
    "PhpOrSomething",
    "PhpTryCatchBlock",
    "PhpValue",
    "PhpValuePossiblyWrapped",
    "PhpSimpleValue",
    "PhpSelectArray",
    "PhpArgumentList",
    "PhpVariableList",
    "PhpFunctionDefinition",
    "PhpFunctionArgumentList",
    "PhpIfStatement",
    "PhpClassDefinition",
    "PhpInterfaceDefinition",
    "PhpInterfaceList",
    "PhpClassBlock",
    "PhpInterfaceBlock",
    "HtmlBlock",
    "HtmlTag",
    "HtmlClosingTag",
    "HtmlTagAttribute",
    "HtmlTextBlock",
    "HtmlComment",
  };
}
/* JavaCC - OriginalChecksum=012c50e5aff05ff74eb932d05bf84379 (do not edit this line) */
