/* Generated By:JavaCC: Do not edit this line. HtmlPageVisitor.java Version 4.1d1 */
package org.openiaml.iacleaner.ast.html;

public interface HtmlPageVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTBlock node, Object data);
  public Object visit(ASTHtmlBlock node, Object data);
  public Object visit(ASTHtmlPhpInlineBlock node, Object data);
  public Object visit(ASTHtmlScriptTag node, Object data);
  public Object visit(ASTHtmlTag node, Object data);
  public Object visit(ASTHtmlClosingTag node, Object data);
  public Object visit(ASTHtmlTagAttribute node, Object data);
  public Object visit(ASTHtmlTextBlock node, Object data);
  public Object visit(ASTHtmlComment node, Object data);
  public Object visit(ASTJsBlock node, Object data);
  public Object visit(ASTPhpBlock node, Object data);
}
/* JavaCC - OriginalChecksum=7e8467fa4ce8245135035919d886d698 (do not edit this line) */
