/* Generated By:JJTree: Do not edit this line. ASTJsNewStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsNewStatement extends SimpleNode {
  public ASTJsNewStatement(int id) {
    super(id);
  }

  public ASTJsNewStatement(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d0ca3ffab40fd07413edd820f2c0a23b (do not edit this line) */
