/* Generated By:JJTree: Do not edit this line. ASTJsBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsBlock extends SimpleNode {
  public ASTJsBlock(int id) {
    super(id);
  }

  public ASTJsBlock(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a8e16185a3e8f8a8fedcd13d53587e51 (do not edit this line) */
