/* Generated By:JJTree: Do not edit this line. ASTJsArgumentList.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsArgumentList extends SimpleNode {
  public ASTJsArgumentList(int id) {
    super(id);
  }

  public ASTJsArgumentList(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=092c0ff637a1751d248b899001bb11ef (do not edit this line) */
