/* Generated By:JJTree: Do not edit this line. ASTJsFunctionDefinition.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsFunctionDefinition extends SimpleNode {
  public ASTJsFunctionDefinition(int id) {
    super(id);
  }

  public ASTJsFunctionDefinition(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=863ca1aa113d611a9061adcd305fb03b (do not edit this line) */
