/* Generated By:JJTree: Do not edit this line. ASTJsReturnStatement.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsReturnStatement extends SimpleNode {
  public ASTJsReturnStatement(int id) {
    super(id);
  }

  public ASTJsReturnStatement(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6d240be18c079ce0cca252c6818796e7 (do not edit this line) */
