/* Generated By:JJTree: Do not edit this line. ASTJsValue.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.js;

public class ASTJsValue extends SimpleNode {
  public ASTJsValue(int id) {
    super(id);
  }

  public ASTJsValue(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8b271f32f1a2156ad82d990b5c15a23f (do not edit this line) */
