/* Generated By:JavaCC: Do not edit this line. JavascriptTreeConstants.java Version 4.1d1 */
package org.openiaml.iacleaner.ast.js;

public interface JavascriptTreeConstants
{
  public int JJTSTARTJS = 0;
  public int JJTJSBLOCK = 1;
  public int JJTJSSTATEMENT = 2;
  public int JJTJSLANGUAGESTATEMENT = 3;
  public int JJTJSTRAVERSEOBJECTS = 4;
  public int JJTJSSELECTARRAY = 5;
  public int JJTJSRETURNSTATEMENT = 6;
  public int JJTJSNEWSTATEMENT = 7;
  public int JJTJSVALUE = 8;
  public int JJTJSVALUEPOSSIBLYWRAPPED = 9;
  public int JJTJSSIMPLEVALUE = 10;
  public int JJTJSARGUMENTLIST = 11;
  public int JJTJSVARIABLELIST = 12;
  public int JJTJSFUNCTIONDEFINITION = 13;
  public int JJTJSFUNCTIONARGUMENTLIST = 14;
  public int JJTJSANONYMOUSFUNCTION = 15;
  public int JJTJSIFSTATEMENT = 16;
  public int JJTJSFORSTATEMENT = 17;
  public int JJTJSFORPARAMETERLIST = 18;
  public int JJTJSFOREVALUATEPARAMETERLIST = 19;
  public int JJTJSINLINEARRAY = 20;
  public int JJTJSTHROWSTATEMENT = 21;
  public int JJTJSTRYCATCHBLOCK = 22;


  public String[] jjtNodeName = {
    "StartJs",
    "JsBlock",
    "JsStatement",
    "JsLanguageStatement",
    "JsTraverseObjects",
    "JsSelectArray",
    "JsReturnStatement",
    "JsNewStatement",
    "JsValue",
    "JsValuePossiblyWrapped",
    "JsSimpleValue",
    "JsArgumentList",
    "JsVariableList",
    "JsFunctionDefinition",
    "JsFunctionArgumentList",
    "JsAnonymousFunction",
    "JsIfStatement",
    "JsForStatement",
    "JsForParameterList",
    "JsForEvaluateParameterList",
    "JsInlineArray",
    "JsThrowStatement",
    "JsTryCatchBlock",
  };
}
/* JavaCC - OriginalChecksum=b5f7b2ca230f767c522cc88a70b4ae7e (do not edit this line) */
