/**
 * 
 */
package org.openiaml.iacleaner.tests;

import java.io.File;

/**
 * Test a complex generated PHP file. File was generated by
 * IAML.
 * 
 * @author Jevon
 *
 */
public class ComplexPhpTest extends IACleanerTestCase {
	
	public File sourceFile = new File("src/org/openiaml/iacleaner/tests/test.php");
	public File targetFile = new File("src/org/openiaml/iacleaner/tests/out.php");
	private String output = null;
	
	@Override
	public void setUp() throws Exception {
		output = clean(sourceFile, targetFile);
		assertNotNull(output);
	}
	
	// any other tests go here
	
}
