/* Generated By:JJTree: Do not edit this line. ASTHtmlBlock.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package org.openiaml.iacleaner.ast.html;

public class ASTHtmlBlock extends SimpleNode {
  public ASTHtmlBlock(int id) {
    super(id);
  }

  public ASTHtmlBlock(HtmlPage p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HtmlPageVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=531efa6454e3d6ee402fa8cd63e793a8 (do not edit this line) */
