/* Generated By:JJTree&JavaCC: Do not edit this line. HtmlPageConstants.java */
package org.openiaml.iacleaner.ast.html;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlPageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HTML_OPEN_TAG = 13;
  /** RegularExpression Id. */
  int HTML_CLOSE_TAG = 14;
  /** RegularExpression Id. */
  int HTML_CLOSE_TAG_XHTML = 15;
  /** RegularExpression Id. */
  int HTML_CLOSING_TAG = 16;
  /** RegularExpression Id. */
  int HTML_TAG_NAME = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_NAME = 19;
  /** RegularExpression Id. */
  int HTML_STRING = 20;
  /** RegularExpression Id. */
  int HTML_ATTRIBUTE_EQUALS = 21;
  /** RegularExpression Id. */
  int HTML_TEXT_BLOCK = 22;
  /** RegularExpression Id. */
  int HTML_COMMENT_START = 23;
  /** RegularExpression Id. */
  int HTML_SCRIPT_TAG = 26;
  /** RegularExpression Id. */
  int JS_SCRIPT = 27;
  /** RegularExpression Id. */
  int PHP_BLOCK_BEGIN = 28;
  /** RegularExpression Id. */
  int PHP_SCRIPT = 29;

  /** Lexical state. */
  int HTML_STATE = 0;
  /** Lexical state. */
  int HTML_TAG_STATE = 1;
  /** Lexical state. */
  int HTML_OPENING_TAG = 2;
  /** Lexical state. */
  int HTML_WITHIN_COMMENT = 3;
  /** Lexical state. */
  int WITHIN_SCRIPT = 4;
  /** Lexical state. */
  int DEFAULT = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\">\"",
    "\"/>\"",
    "\"</\"",
    "<HTML_TAG_NAME>",
    "<LETTER>",
    "<HTML_ATTRIBUTE_NAME>",
    "<HTML_STRING>",
    "\"=\"",
    "<HTML_TEXT_BLOCK>",
    "\"<!--\"",
    "\"-->\"",
    "<token of kind 25>",
    "<HTML_SCRIPT_TAG>",
    "<JS_SCRIPT>",
    "\"<?php\"",
    "<PHP_SCRIPT>",
  };

}
