/* Generated By:JavaCC: Do not edit this line. HtmlPageTreeConstants.java Version 4.1d1 */
package org.openiaml.iacleaner.ast.html;

public interface HtmlPageTreeConstants
{
  public int JJTSTART = 0;
  public int JJTBLOCK = 1;
  public int JJTHTMLBLOCK = 2;
  public int JJTHTMLPHPINLINEBLOCK = 3;
  public int JJTHTMLSCRIPTTAG = 4;
  public int JJTHTMLTAG = 5;
  public int JJTHTMLCLOSINGTAG = 6;
  public int JJTHTMLTAGATTRIBUTE = 7;
  public int JJTHTMLTEXTBLOCK = 8;
  public int JJTHTMLCOMMENT = 9;
  public int JJTJSBLOCK = 10;
  public int JJTPHPBLOCK = 11;


  public String[] jjtNodeName = {
    "Start",
    "Block",
    "HtmlBlock",
    "HtmlPhpInlineBlock",
    "HtmlScriptTag",
    "HtmlTag",
    "HtmlClosingTag",
    "HtmlTagAttribute",
    "HtmlTextBlock",
    "HtmlComment",
    "JsBlock",
    "PhpBlock",
  };
}
/* JavaCC - OriginalChecksum=4fe803b848fb99b1df38360bc3786d52 (do not edit this line) */
